# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            rehash.fm
subtitle:         tech podcast for everyone
description:      rehash.fm はインターネットと酒をこよなく愛する @smile_0yen と釣りとアニメに人生を懸ける @azihsoyn の２人のエンジニアが最近気になっている技術情報などをお送りするまったり系Tech Podcastです。
keywords:         podcast technology
language:         "ja" # default language of the blog. Language codes: http://www.w3schools.com/tags/ref_language_codes.asp

baseurl:          "" # the subpath of your site, e.g. /blog
url:              "https://rehash.fm" # the base hostname & protocol for your site. Have a look at robots.txt as well!
permalink:        /:title
cover:            /assets/cover_v2.jpg
disqus_shortname: "jekylldecent"

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
include: ['_pages']
exclude: [vendor]
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
